kowainik/kowainik.github.io

- .travis.yml
> [#3] Add travis config

- posts/2018-06-21-haskell-build-tools.md
I need to test some of the commands before publishing. But can do it only from my Ubuntu machine.
> Add some changes to build-tools blog post

- .gitignore
- css/default.css
- css/post.css
- js/stars.js
- site.hs
- src/Kowainik/Readme.hs
- templates/readme.html
- templates/readmes.html
- website.cabal
> [#13] Get project pages unde projects/ link

- site.hs
- src/Kowainik/Team.hs
- team.json
> [#29] Read team members via json file

- templates/404.html
- templates/main.html
> Add meta data

- templates/footer.html
> [#25] Add Hakyll link at the main page

- css/post.css
- posts/2018-09-09-dhall-to-hlint.md
> [#35] Add Dhall to Hlint post

- templates/main.html
- templates/posts-default.html
The start of #40 (I don't know the good and easy way for resolving that issue)
> Add google analytics

- website.cabal
Resolves #44 
Probably not all upper bounds are required, but I've added all just in case.
> [#44] Build with cabal

- .gitignore
- css/post.css
- posts-raw/2018-09-25-co-log.md
> [#32] Add co-log blog post

- posts-raw/2018-09-25-co-log.md
- site.hs
- templates/404.html
- templates/post.html
- templates/posts.html
- templates/readme.html
- templates/readmes.html
- website.cabal
> [#51] Make all links w/o html extension

- posts-raw/2018-08-19-picnic-put-containers-into-a-backpack.md
> [#46] Add link to the video

- posts-raw/2018-10-01-hacktoberfest.md
> [#54] Add Hacktoberfest announcement

- posts-raw/2018-11-18-state-pattern-matching.md
> [#62] Add state pattern matching blog post

- posts-raw/2018-06-21-haskell-build-tools.md
- posts-raw/2018-07-11-typerep-map-step-by-step.md
- posts-raw/2018-08-19-picnic-put-containers-into-a-backpack.md
- posts-raw/2018-09-09-dhall-to-hlint.md
- stack.yaml
- website.cabal
I've bumped to GHC-8.6.3. Also I've updated content of some old blog posts. Mostly maintenance update to keep them up-to-date with :two: :zero: :one: :nine: :slightly_smiling_face:
> Migrate to GHC 8.6.3 and update some blog posts

- css/default.css
- css/post.css
Should resolve #69
@willbasky, I know it's too much to ask for, but if you will have a chance, can you please build the project and check if it works on your screen?
@ChShersh , please also check. Tags became significantly smaller, so let me know if I should make this only for small screens..
> Maake font in tags smaller so it can fit small screens

- css/post.css
- js/post.js
- kowainik-site.cabal
- site.hs
- templates/post.html
- templates/posts-default.html
> [#43] Impl interactive toc and anchors on hover

- .travis.yml
- README.md
- kowainik-site.cabal
- site.hs
- src/Kowainik/Feed.hs
- stack.yaml
Resolves #68
I also did some cleanup of the package metadata.
> [#68] Add RSS and Atom feeds

- posts/2018-09-25-co-log.md
- posts/2018-11-18-state-pattern-matching.md
- posts/2019-01-14-tomland.md
* Update tomland benchmarks
* Fix strange quotes in some blog posts
> Minor updates to blog posts

- src/Kowainik/Readme.hs
- templates/posts.html
- templates/readmes.html
> [#85] Improve projects page

- kowainik-site.cabal
- posts/2018-07-11-typerep-map-step-by-step.md
- site.hs
> [#88] Introduce hakyll-shortcut-links

- css/default.css
- css/post.css
- posts/2018-07-11-typerep-map-step-by-step.md
- posts/2018-08-19-picnic-put-containers-into-a-backpack.md
- posts/2018-09-25-co-log.md
- posts/2019-01-14-tomland.md
- posts/2019-07-23-membrain.md
- templates/posts-default.html
Improve images
Fix font in posts
improve tables
> Add membrain blog post

- css/post.css
- posts/2019-09-25-gsoc2019.md
- site.hs
- templates/404.html
- templates/main.html
- templates/posts-default.html
> [#99] GSoC 2019 post

- posts/2018-09-09-dhall-to-hlint.md
> [#97] Update dhall-to-hlint blog post

- src/Kowainik/Readme.hs
> [#113] Fetch more pages of projects

- css/default.css
- css/post.css
> [#122] Improve inline code blocks

- README.md
- posts/2018-09-09-dhall-to-hlint.md
- templates/post.html
> [#24] `last modified` field for posts

- templates/posts-default.html
> [#127] Improve keywords metadata in posts

- cabal.project
- src/Kowainik.hs
- src/Kowainik/Readme.hs
Resolves #119
Resolves #115
Run like:
```
NO_SYNC=1 crun site rebuild
```
or
```
NO_SYNC=1 crun site watch
```
it takes 46 seconds with sync and only 13 seconds with `NO_SYNC`
> [#119] Add --no-sync flag

- src/Kowainik/Social.hs
- src/Kowainik/Team.hs
- team/creators.json
- templates/main.html
- templates/team.html
> [#79] Links to websites of teammembers

- .github/workflows/ci.yml
- posts/2018-09-09-dhall-to-hlint.md
- posts/2019-01-14-tomland.md
- scripts/deploy.sh
- src/Kowainik/Download.hs
- src/Kowainik/Readme.hs
> [#143] Use main default branch

- .github/dependabot.yml
> [#149] Add dependabot

- css/post.css
- posts/2020-12-13-naming-conventions.md
> [#155] Naming conventions blog post
